### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by greatpatton** [yrjsg/flume-kafka#1]
Hello,

I tried to build the project with maven 3.1 but it is missing 2 dependencies:

com.linkedin.kafka:kafka:jar:0.7.2, com.vipshop.scala:scala:jar:2.8.0

I was able to find the com.linkedin.kafka but the other one seems very linked to your own code.

Will it be possible to include this 2 dependencies to allow the build?

Anyways thanks a lot for your piece of code!

**Comment by yrjsg** [comment]
Oops, it seems like I've use some own dependency in build environment. I would fix that ASAP when I am in office.

**Comment by yrjsg** [comment]
I've searched kafka-0.7.2.jar in http://mvnrepository.com/ but found nothing. I upload in extra-dependencies directory and you can download it and make it available in your own repo.

For scala, I've modified pom.xml to use scala jar of official mvn repo.
