### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.flume.ChannelFactory.getClass(Ljava/lang/String;)Ljava/lang/Class;

### ISSUE THREAD

**Issue by jconerly** [yrjsg/flume-kafka#5]
I'm attempting to use the kafka source functionality.

After building the jar (with dependencies) and copying into the flume directory with all the other source/sink .jar files, I am getting this error when running flume-ng

https://gist.github.com/jconerly/81dffe5c8e9f59760a98

The following is the source configuration:

```
agent.sources.kafka_source.type       = com.vipshop.flume.source.kafka.KafkaSource
agent.sources.kafka_source.zk.connect = 127.0.0.1:2181
agent.sources.kafka_source.topic      = data
agent.sources.kafka_source.groupid    = data-client
agent.sources.kafka_source.batch.size = 100
```

I had to modify the pom.xml to include the maven-assembly-plugin so I could build a jar that included all the dependencies. I tried deploying the regular jar first and flume complained of missing dependencies like so:

```
13/11/26 21:23:27 ERROR node.PollingPropertiesFileConfigurationProvider: Failed to start agent because dependencies were not found in classpath. Error follows.
java.lang.NoClassDefFoundError: kafka/consumer/ConsumerConfig
```

I am running Flume 1.3.1, and Kafka 0.7.2-incubating

Please advise, I'd love to get this up and running.

**Comment by yrjsg** [comment]
Is there kafka-0.7.2.jar in your class path?

**Comment by jconerly** [comment]
Yes, it is.

**Comment by kwachsmuth** [comment]
could you solve this? same exception here, using flume-ng 1.4 and having kafka-0.7.2.jar in classpath

01 Aug 2014 10:47:54,635 ERROR [conf-file-poller-0](org.apache.flume.node.PollingPropertiesFileConfigurationProvider$FileWatcherRunnable.run:145)  -
 Failed to start agent because dependencies were not found in classpath. Error follows.
java.lang.NoClassDefFoundError: kafka/consumer/ConsumerConfig

**Comment by yrjsg** [comment]
confirm you are using kafka 0.7 in your classpath. kafka 0.7 is not in official maven repo, so you need to deploy it in your local maven repo
